# Generated by Django 5.2.6 on 2025-11-13 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questpaper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('topic', 'Topic'), ('question_count', 'Question Count'), ('subject', 'Subject'), ('grade', 'Grade'), ('complexity', 'Complexity'), ('term', 'Term'), ('school', 'School')], max_length=100)),
                ('pattern', models.TextField(help_text='Regex pattern for extraction')),
                ('priority', models.IntegerField(default=1, help_text='Lower numbers = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Pattern description and usage')),
            ],
            options={
                'verbose_name': 'Extraction Pattern',
                'verbose_name_plural': 'Extraction Patterns',
                'ordering': ['field_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-id'], 'verbose_name': 'Question Paper', 'verbose_name_plural': 'Question Papers'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='educator',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='auto_detected_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='extraction_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_question_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='complexity_rating',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questpaper.department'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='file',
            field=models.FileField(upload_to='question_papers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='question_papers', to='questpaper.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questpaper.grade'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questpaper.school'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questpaper.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questpaper.subject'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questpaper.term'),
        ),
    ]
