# Generated by Django 5.2.6 on 2025-12-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_student_circuit_alter_student_course_and_more'),
        ('questpaper', '0002_extractionpattern_grade_school_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.grade'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.school'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.term'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
