# Generated by Django 5.2.6 on 2026-01-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questpaper', '0003_alter_questionpaper_grade_alter_questionpaper_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='name',
            field=models.CharField(blank=True, help_text='Display name of the question paper', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='title',
            field=models.CharField(blank=True, help_text='Name of the question paper (auto-filled from filename if empty)', max_length=255, null=True),
        ),
    ]
