# Generated by Django 5.2.6 on 2026-01-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
