# Generated by Django 5.2.6 on 2026-01-29 06:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0003_remove_university_user_delete_application_and_more'),
        ('bursary', '0001_initial'),
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('huggingface', 'Hugging Face')], max_length=20)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.URLField(blank=True, max_length=500, null=True)),
                ('model_name', models.CharField(default='gpt-4-turbo-preview', help_text='gpt-4-turbo-preview, claude-3-opus-20240229, etc.', max_length=100)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='1 = highest priority')),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('requests_per_day', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Service',
                'verbose_name_plural': 'AI Services',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(help_text='Enter Full Names as they appear on ID', max_length=200, verbose_name='Full Names')),
                ('address', models.TextField(help_text='Enter complete address with postal code', max_length=1000, verbose_name='Full Address')),
                ('disability', models.TextField(blank=True, help_text="State any disabilities or 'No' if none", max_length=500, null=True, verbose_name='Disability Information')),
                ('university_manual', models.CharField(blank=True, help_text='If not in list above, enter university name here', max_length=500, null=True, verbose_name='University Name (Manual Entry)')),
                ('bursary_manual', models.CharField(blank=True, help_text='If not in list above, enter bursary name here', max_length=200, null=True, verbose_name='Bursary Name (Manual Entry)')),
                ('details', models.TextField(help_text='Courses/Faculty, Gender, Marital-status, Home Language, Citizenship, Race, Email, Phone, ID Number, Birth Date, School Name', max_length=2000, verbose_name='Application Details')),
                ('next_of_kin', models.TextField(blank=True, help_text='Full name, address, phone numbers of next of kin', max_length=1000, null=True, verbose_name='Next of Kin Details')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a clear profile photo', null=True, upload_to='applications/profiles/%Y/%m/%d/', verbose_name='Profile Photo')),
                ('introduction_video', models.FileField(blank=True, help_text='Optional: Short introduction video', null=True, upload_to='applications/videos/%Y/%m/%d/', verbose_name='Introduction Video')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\+\\-\\(\\)]+$', 'Enter a valid phone number')], verbose_name='Phone Number')),
                ('id_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='ID/Passport Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('home_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Home Language')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Citizenship')),
                ('race', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('coloured', 'Coloured'), ('indian', 'Indian/Asian'), ('other', 'Other')], max_length=50, null=True)),
                ('course_faculty', models.CharField(blank=True, max_length=500, null=True, verbose_name='Course/Faculty Choice')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='High School Name')),
                ('matric_year', models.IntegerField(blank=True, null=True, verbose_name='Matriculation Year')),
                ('target_form_url', models.URLField(blank=True, help_text="Paste the exact URL of the university's online application form", max_length=2000, null=True, verbose_name='University Application Form URL')),
                ('automation_status', models.CharField(choices=[('draft', '📝 Draft'), ('ready', '✅ Ready for Automation'), ('analyzing', '🔍 Analyzing Form'), ('filling', '🖊️ Filling Form'), ('waiting_review', '👀 Waiting for Review'), ('completed', '🎉 Form Filled'), ('submitted', '📤 Submitted'), ('failed', '❌ Failed')], default='draft', max_length=20, verbose_name='Automation Status')),
                ('automation_log', models.JSONField(blank=True, default=list, verbose_name='Automation Activity Log')),
                ('field_mapping', models.JSONField(blank=True, null=True, verbose_name='Detected Field Mapping')),
                ('screenshots', models.JSONField(blank=True, default=list, verbose_name='Automation Screenshots')),
                ('submission_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='University Reference Number')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Submission Date')),
                ('status', models.CharField(choices=[('draft', '📝 Draft'), ('ready', '✅ Ready for Automation'), ('analyzing', '🔍 Analyzing Form'), ('filling', '🖊️ Filling Form'), ('waiting_review', '👀 Waiting for Review'), ('completed', '🎉 Form Filled'), ('submitted', '📤 Submitted'), ('failed', '❌ Failed')], default='draft', max_length=20, verbose_name='Application Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('priority', models.IntegerField(default=1, help_text='Higher number = higher priority', verbose_name='Priority Level')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_automation_attempt', models.DateTimeField(blank=True, null=True)),
                ('preferred_ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.aiservice', verbose_name='Preferred AI Service')),
                ('selected_bursaries', models.ManyToManyField(blank=True, help_text='Select one or more bursaries to apply for', to='bursary.bursary', verbose_name='Selected Bursaries')),
                ('selected_university', models.ForeignKey(blank=True, help_text='Choose from existing universities', null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.collegeanduniversities', verbose_name='Selected University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('target_url', models.URLField(max_length=2000)),
                ('browser_type', models.CharField(default='chromium', max_length=50)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=200, null=True)),
                ('detected_fields', models.JSONField(blank=True, default=list)),
                ('filled_fields', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '📝 Draft'), ('ready', '✅ Ready for Automation'), ('analyzing', '🔍 Analyzing Form'), ('filling', '🖊️ Filling Form'), ('waiting_review', '👀 Waiting for Review'), ('completed', '🎉 Form Filled'), ('submitted', '📤 Submitted'), ('failed', '❌ Failed')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ai_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.aiservice')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='application.application')),
            ],
            options={
                'verbose_name': 'Automation Session',
                'verbose_name_plural': 'Automation Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'created_at'], name='application_student_54e07f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='application_status_c09e34_idx'),
        ),
    ]
