# Generated by Django 5.2.6 on 2026-01-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='applications_multiple', to='college.collegeanduniversities', verbose_name='Selected Universities (Multiple)'),
        ),
    ]
