# Generated by Django 5.2.6 on 2025-11-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_staff_course_remove_student_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='course',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='session',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='term',
        ),
        migrations.AddField(
            model_name='educator',
            name='grades',
            field=models.ManyToManyField(to='main_app.grade'),
        ),
    ]
