# Generated by Django 5.2.6 on 2025-11-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_educator_circuit_remove_educator_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='school',
        ),
        migrations.RemoveField(
            model_name='member',
            name='session',
        ),
        migrations.RemoveField(
            model_name='member',
            name='term',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='course',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='term',
        ),
    ]
