# Generated by Django 5.2.6 on 2025-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_member_school_remove_member_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='subject',
        ),
        migrations.AddField(
            model_name='principal',
            name='grades',
            field=models.ManyToManyField(to='main_app.grade'),
        ),
        migrations.AddField(
            model_name='principal',
            name='subjects',
            field=models.ManyToManyField(to='main_app.subject'),
        ),
    ]
