# Generated by Django 5.2.6 on 2025-11-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_subject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='circuit',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='main_app.circuit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.PROTECT, to='main_app.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=342, on_delete=django.db.models.deletion.PROTECT, to='main_app.school'),
            preserve_default=False,
        ),
    ]
